spring:
  application:
    name: ad-eureka
server:
  port: 8000
eureka:
  instance:
    hostame: localhost
  client:
    fetch-registry: false # 不需要获取客户端信息
    register-with-eureka: false # 不需要注册到其他registry center
    service-url:
      defaultZone: http://${eureka.instance.hostame}:${server.port}/eureka/

---
#spring:
#  application:
#    name: ad-eureka
#  profiles:server1
#server:
#  port: 8001
#eureka:
#  instance:
#    hostame: server1
#    prefer-ip-address: false
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/
---
#spring:
#  application:
#    name: ad-eureka
#  profiles:server2
#server:
#  port: 8000
#eureka:
#  instance:
#    hostame: server1
#    prefer-ip-address: false
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/

---
#spring:
#  application:
#    name: ad-eureka
#  profiles:server2
#server:
#  port: 8002
#eureka:
#  instance:
#    hostame: server3
#    prefer-ip-address: false
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/

